version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - ">= 8.a, < 9"
  - dependency-name: date-fns
    versions:
    - 2.20.2
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pg_query
    versions:
    - "> 1.3.0"
  - dependency-name: pg_query
    versions:
    - ">= 2.a, < 3"
  - dependency-name: rubocop-rails_config
    versions:
    - 1.2.2
    - 1.5.1
  - dependency-name: exiftool_vendored
    versions:
    - 12.17.0
  - dependency-name: turbo-rails
    versions:
    - 0.5.9
