inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Layout/EmptyLines:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Lint/Debugger:
  Enabled: true
