app:
  tty: true
  stdin_open: true
  command: foreman start
  build: "./.build/docker"
  links:
    - redis
    - postgres
    - mailcatcher
  volumes:
    - ./:/app
    - ~/.bash_history:/root/.bash_history
    - .build/.bundle-cache-dir/app:/usr/local/bundle/
    - /tmp:/tmp
  ports:
    - "3035:3035"
  environment:
    - DOCKER=true
    - RUBYOPT=-W:no-deprecated -W:no-experimental
    - REDIS_URL=redis://redis:6379/4
    - DEVELOPER=true
    - OPENSSL_CONF=/etc/ssl/

redis:
  image: redis:alpine

postgres:
  image: postgres:12-alpine
  volumes:
    - .build/.db:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=1234

nginx:
  build: "./.build/nginx"
  ports:
    - "3000:80"
  volumes:
    - .build/nginx/sites-enabled:/etc/nginx/sites-enabled
    - ./public:/app/public
    - /tmp:/tmp
  links:
    - app

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - '1080:1080'
    - '1025'
