default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: psm_development
test:
  <<: *default
  database: psm_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DATABASE_POOL"] %>
