default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DEV_PG_USER") { "postgres" } %>
  password: <%= ENV.fetch("DEV_PG_PASSWORD") { "1234" } %>
  host: <%= ENV.fetch("DEV_PG_HOST") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: psm_development
test:
  <<: *default
  database: psm_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= Etc.nprocessors * 5 %>