name: Verify
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Run linters
        run: |
          bundle exec rubocop --parallel
          yarn eslint --ext .js --ext .jsx app/javascript
      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
#          bundle exec brakeman -q -w2

  tests:
    name: Tests
    runs-on: ubuntu:bionic
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: "1234"
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Install ubuntu deps
        env:
          VIPS_VERSION: 8.10.2
          VIPS_URL: https://github:com/libvips/libvips/releases/download
        run: |
          sudo apt-get update -y && sudo apt-get install -y \
          	wget \
          	glib-2.0-dev \
          	libexpat-dev \
          	librsvg2-dev \
          	libpng-dev \
          	libgif-dev \
          	libjpeg-dev \
          	libexif-dev \
          	liblcms2-dev \
          	libheif-dev \
          	liborc-dev \
          	time

          sudo cd /usr/local/src \
            && sudo wget ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
          	&& tar xzf vips-${VIPS_VERSION}.tar.gz \
          	&& sudo cd vips-${VIPS_VERSION} \
          	&& sudo ./configure \
          	&& sudo make \
          	&& sudo make install \
          	&& sudo ldconfig
      - name: Setup test database
        env:
          RAILS_ENV: test
          DEV_PG_HOST: localhost
          DEV_PG_USER: myapp
          DEV_PG_PASSWORD: 1234
        run: |
          bundle exec rails db:setup

      - name: Run tests
        env:
          RAILS_ENV: test
          DEV_PG_HOST: localhost
          DEV_PG_USER: myapp
          DEV_PG_PASSWORD: 1234
        run: |
          bundle exec rspec